### PR TITLE
Fix broken link to commcare-updates

### PR DESCRIPTION
**Pull request by benrudolph**
@TylerSheffels 

http://manage.dimagi.com/default.asp?183623#1024437

### CODE REVIEW

**Comment by benrudolph** [comment]
@TylerSheffels do i have to deploy proxy in order for this to update?

**Comment by TylerSheffels** [comment]
@benrudolph Yes, you will need to deploy_proxy for this to take effect.

**Comment by TylerSheffels** [comment]
@benrudolph FYI I ran deploy_proxy on both prod and india

**Comment by benrudolph** [comment]
thanks

**Comment by TylerSheffels** [comment]
No sweat, realized I was already deploying proxy to india to figure out
the cert stuff.

**Pull request merged**
